
export const POST_TOKEN = 'POST_TOKEN';
export const POST_TOKEN_SUCCESS = 'POST_TOKEN_SUCCESS';
export const POST_TOKEN_FAILURE = 'POST_TOKEN_FAILURE';
export const BLACK_LIST_TOKEN = 'BLACK_LIST_TOKEN';
export const BLACK_LIST_TOKEN_SUCCESS = 'BLACK_LIST_TOKEN_SUCCESS';
export const BLACK_LIST_TOKEN_FAILURE = 'BLACK_LIST_TOKEN_FAILURE';