version: '3.7'

services:

  frontend:
    container_name: fe
    command: npm start
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    ports:
      - 5000:5000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CI=true

  backend:
    container_name: be
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
        - ./backend:/backend
    ports:
        - 8000:8000
    expose:
        - 8000
    env_file:
        - ./backend/.env
    command: /backend/entrypoint-backend.sh

  db:
    container_name: db
    image: mysql:8
    restart: always
    command:
        - '--default-authentication-plugin=mysql_native_password'
        - '--character-set-server=utf8'
    ports:
        - 3306:3306
    expose:
        - '3306'
    volumes:
        - ./backend/db:/var/lib/mysql
    env_file:
        - ./backend/.env
