version: '3.7'

services:

  frontend:
    # container_name: sample
    command: npm build
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    ports:
      - 5000:5000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    # container_name: sample
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
        - ./backend:/backend
    ports:
        - 8000:8000
    env_file:
        - ./backend/.env
    depends_on:
        - db

  db:
    image: mysql:8
    restart: always
    command:
        - '--default-authentication-plugin=mysql_native_password'
        - '--character-set-server=utf8'
    ports:
        - 3306:3306
    volumes:
        - ./backend/db:/var/lib/mysql
    env_file:
        - ./backend/.env

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/frontend
    depends_on:
      - backend
      - frontend