version: "3"

services:
    db:
        container_name: db
        image: mysql:8
        restart: always
        command: 
            - '--default-authentication-plugin=mysql_native_password'
            - '--character-set-server=utf8'
        ports:
            - '${DB_PORT}:${DB_PORT}'
        expose:
            - "${DB_PORT}"
        volumes:
            - ./backend/db:/var/lib/mysql
            - ./frontend/:/frontend/
        environment:
            MYSQL_HOST: ${DB_HOST}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    backend:
        container_name: backend
        build: ./backend
        volumes:
            - ./backend/:/backend
        ports:
            - "${BE_PORT}:${BE_PORT}"
        depends_on:
            - db
        links:
            - db
              #frontend:
              #container_name: frontend
              #build: ./frontend
              #volumes:
              #- ./frontend/:/frontend/
              #ports:
              #- "${FE_PORT}:80"
