export const GET_SONG_LIST = 'GET_SONG_LIST';
export const GET_SONG_LIST_SUCCESS = 'GET_SONG_LIST_SUCCESS';
export const GET_SONG_LIST_FAILURE = 'GET_SONG_LIST_FAILURE';

export const POST_SONG_LIST = 'POST_SONG_LIST';
export const POST_SONG_LIST_SUCCESS = 'POST_SONG_LIST_SUCCESS';
export const POST_SONG_LIST_FAILURE = 'POST_SONG_LIST_FAILURE';


