# Generated by Django 3.1.3 on 2020-11-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=20)),
                ('user_location', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'song',
            },
        ),
    ]
