export const GET_HELLO_WORLD = 'GET_HELLO_WORLD';
export const GET_HELLO_WORLD_SUCCESS = 'GET_HELLO_WORLD_SUCCESS';
export const GET_HELLO_WORLD_FAILURE = 'GET_HELLO_WORLD_FAILURE';

export const POST_HELLO_WORLD = 'POST_HELLO_WORLD';
export const POST_HELLO_WORLD_SUCCESS = 'POST_HELLO_WORLD_SUCCESS';
export const POST_HELLO_WORLD_FAILURE = 'POST_HELLO_WORLD_FAILURE';