name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master


jobs:
  backend-linter:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: flake8 --max-line-length 120 backend/

  backend-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v2
      - name: Build the Stack
        run:  docker-compose -f docker-compose-local.yml build backend

      - name: Make DB Migrations
        run:  docker-compose -f docker-compose-local.yml run --rm backend python manage.py migrate

      - name: Run the Stack
        run:  docker-compose -f docker-compose-local.yml up -d backend

      - name: Run Django Tests
        run:  docker-compose -f docker-compose-local.yml run --rm backend python manage.py test

  # frontend-linter:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js 6.x
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 6.x
  #   - uses: actions/checkout@v2
  #   - run: |
  #       cd frontend
  #       npm install eslint
  #       eslint --max-warnings 1 src

  # frontend-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Use Node.js 6.x
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 6.x
  #   - uses: actions/checkout@v2
  #   - run: |
  #       cd frontend
  #       npm install
  #       npm test --all --forceExit --ci
