name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  backend-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Lint with flake8
        run: docker-compose -f docker-compose-local.yml run --rm backend flake8 --max-line-length 120 .

  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Run Django Tests
        run:  docker-compose -f docker-compose-local.yml run --rm backend python manage.py test

  frontend-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Run eslint
        run: docker-compose -f docker-compose-local.yml run --rm frontend eslint --max-warnings 0 src

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v2

      - name: Run npm tests
        run: docker-compose -f docker-compose-local.yml run --rm frontend npm test
