name: Deploy

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/musichub"

    - name: Run the build on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: docker-compose -f musichub/docker-compose-production.yml down &&
                docker-compose -f musichub/docker-compose-production.yml up -d --build frontend &&
                docker-compose -f musichub/docker-compose-production.yml up -d --build backend &&
                docker-compose -f musichub/docker-compose-production.yml up -d --build db &&
                docker-compose -f musichub/docker-compose-production.yml up -d --build nginx &&
